campy/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    # admin list
    path('admin/', admin.site.urls),
    path('login/', views.LoginTV.as_view(), name='login'),
    path('accounts/', include('allauth.urls')),

    # ui list
    path('', views.IndexTV.as_view(), name='index'),
    path('test/', views.test, name='test'),

    # app ui list
    path('student/', include('student.urls'), name='student'),
    path('history/', include('history.urls'), name='history'),
    path('graduation/', include('graduation.urls'), name='graduation'),
    path('schedule/', include('schedule.urls'), name='schedule'),
    path('university/', include('university.urls'), name='university'),
    path('lecture/', include('lecture.urls'), name='lecture'),

]

schedule/urls.py
from django.urls import path
from . import views

urlpatterns = [
    #path('', views.ScheduleLV.as_view(), name='schedule_list'),
    path('add/', views.ScheduleCV.as_view(), name='schedule_add'),
    path('<int:pk>/update/', views.ScheduleUV.as_view(),
         name='schedule_update'),
]

university/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from . import views

router = DefaultRouter()
router.register(r'department', views.DepartmentViewset)
router.register(r'university', views.UniversityGradeViewset)
router.register(r'community', views.CommunityViewset)
router.register(r'division', views.DivisionViewset)
router.register(r'area', views.AreaViewset)
router.register(r'track', views.TrackViewset)

urlpatterns = [
    #대학 CRU
    path('', views.UniversityLV.as_view(),
         name='university_list'),
    path('add/', views.UniversityCV.as_view(),
         name='university_add'),
    path('<int:pk>/update/', views.UniversityUV.as_view(),
         name='university_update'),
    path('<int:pk>/delete/', views.UniversityDeleteV.as_view(),
         name='university_delete'),

    #대학 데이터 CRU (이수구분, 영역, 트랙)
    path('data/', views.UniversityDataLV.as_view(),
         name='university_data_list'),
    path('data/<int:pk>/', views.UniversityDataDV.as_view(),
         name='university_data_detail'),

    #학과 데이터 CRU
    path('department/', views.DepartmentUniversityLV.as_view(),
         name='department_university_list'),
    path('department/<int:university>/', views.DepartmentLV.as_view(),
         name='department_list'),
    path('department/<int:university>/add/', views.DepartmentCV.as_view(),
         name='department_add'),
    path('department/<int:university>/<int:pk>/update/', views.DepartmentUV.as_view(),
         name='department_update'),
    path('department/<int:university>/<int:pk>/delete/', views.DepartmentDeleteV.as_view(),
         name='department_delete'),

    #커뮤니티 그룹
    path('community/', views.CommunityLV.as_view(),
         name='community_list'),

    #API
    path('api/', include(router.urls)),
]

graduation/models.py
from django.db import models
from university.models import CompletionDivision, Track, University, Department

# Create your models here.
class SubjectGroup(models.Model):
    university = models.ForeignKey(University, verbose_name='대학', on_delete=models.CASCADE)
    name = models.CharField(verbose_name='그룹명', max_length=20)
    completion_divisions = models.ManyToManyField(CompletionDivision, verbose_name='이수구분들')

class RuleGeneral(models.Model):
    RULE_TYPE_CHOICES = (
        (1, '학점총합'),
        (2, '과목갯수'),
        (3, '영역갯수'),
        (4, '학점평균'),
    )
    university = models.ForeignKey(University, verbose_name='대학', on_delete=models.CASCADE)
    name = models.CharField(verbose_name='졸업요건명', max_length=20)
    track = models.ForeignKey(Track, verbose_name='트랙', on_delete=models.CASCADE)
    year = models.SmallIntegerField(default=0)
    type = models.SmallIntegerField(verbose_name='졸업요건타입', choices=RULE_TYPE_CHOICES, default=1)
    value = models.SmallIntegerField(verbose_name='졸업요건값', default=0)
    subject_group = models.ForeignKey(SubjectGroup, verbose_name='과목그룹', on_delete=models.CASCADE)

class RuleSpecific(models.Model):
    RULE_TYPE_CHOICES = (
        (1, '학점총합'),
        (2, '과목갯수'),
        (3, '영역갯수'),
        (4, '학점평균'),
    )
    university = models.ForeignKey(University, verbose_name='대학', on_delete=models.CASCADE)
    department = models.ForeignKey(Department, verbose_name='학과', on_delete=models.CASCADE)
    name = models.CharField(verbose_name='졸업요건명', max_length=20)
    track = models.ForeignKey(Track, verbose_name='트랙', on_delete=models.CASCADE)
    year = models.SmallIntegerField(default=0)
    type = models.SmallIntegerField(verbose_name='졸업요건타입', choices=RULE_TYPE_CHOICES, default=1)
    value = models.SmallIntegerField(verbose_name='졸업요건값', default=0)
    upper_rule = models.ForeignKey(RuleGeneral, verbose_name='상위졸업요건', on_delete=models.CASCADE, null=True, blank=True)
    change_rule = models.ForeignKey('self', verbose_name='특정룰 변경', on_delete=models.CASCADE, null=True, blank=True)
    subject_group = models.ForeignKey(SubjectGroup, verbose_name='과목그룹', on_delete=models.CASCADE)

schedule/models.py
from django.db import models
from django.contrib.auth.models import User
from lecture.models import Lecture

# Create your models here.
class Schedule(models.Model):
    user = models.ForeignKey(User, verbose_name='유저', on_delete=models.CASCADE)
    name = models.CharField(verbose_name='시간표이름', max_length=20)
    lectures = models.ManyToManyField(Lecture, verbose_name='강의들')

university/models.py
from django.db import models

# Create your models here.

class University(models.Model):
    FIRST = 4.5
    SECOND = 4.3
    THIRD = 4.0
    CREDIT_CHOICES = (
        (FIRST, '4.5'),
        (SECOND, '4.3'),
        (THIRD, '4.0'),
    )

    name = models.CharField(verbose_name='대학이름', max_length=30)
    # minimum_credit = models.FloatField(verbose_name='최소학점')
    maximum_credit = models.FloatField(verbose_name='최대학점', default=4.5, choices=CREDIT_CHOICES)

class CompletionDivision(models.Model):
    university = models.ForeignKey(University, verbose_name='대학', on_delete=models.CASCADE)
    name = models.CharField(verbose_name='이수구분이름', max_length=10)
    abbreviation = models.CharField(verbose_name='약어', max_length=10, blank=True)
    group_name = models.CharField(verbose_name='그룹이름', max_length=10, blank=True)

    def get_division_by_university(university_id):
        return CompletionDivision.objects.filter(university=university_id)

class Area(models.Model):
    university = models.ForeignKey(University, verbose_name='대학', on_delete=models.CASCADE)
    name = models.CharField(verbose_name='영역이름', max_length=10)
    abbreviation = models.CharField(verbose_name='약어', max_length=10, blank=True)

    def get_area_by_university(university_id):
        return Area.objects.filter(university=university_id)

class Community(models.Model):
    name = models.CharField(verbose_name='커뮤니티이름', max_length=20)

class Track(models.Model):
    university = models.ForeignKey(University, verbose_name='대학', on_delete=models.CASCADE)
    name = models.CharField(verbose_name='트랙이름', max_length=20)

    def get_track_by_university(university_id):
        return Track.objects.filter(university=university_id)

class Department(models.Model):
    university = models.ForeignKey(University, verbose_name='대학', on_delete=models.CASCADE)
    name = models.CharField(verbose_name='학과이름', max_length=20)
    college_name = models.CharField(verbose_name='단과대학이름', max_length=20)
    same_department = models.ForeignKey('self', verbose_name='동일학과', on_delete=models.CASCADE, blank=True, null=True)
    community = models.ForeignKey(Community, verbose_name='커뮤니티그룹', on_delete=models.CASCADE, blank=True, null=True)

schedule/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView, UpdateView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from lecture.models import Lecture
from student.mixin import DefaultMixin, LoginRequiredMixin
from student.models import StudentInfo
from university.models import CompletionDivision
from .models import Schedule
# Create your views here.

class ScheduleLV(DefaultMixin, LoginRequiredMixin, ListView):
    model = Schedule
    #현재 html파일 없음
    template_name = 'schedule_list.html'
    active = 'scheduleActive'

class ScheduleCV(DefaultMixin, LoginRequiredMixin, CreateView):
    model = Schedule
    template_name = 'schedule_form.html'
    fields = ('name', 'lectures')
    active = 'scheduleActive'
    success_url = '/schedule/'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)

        #학생데이터로 대학 정보 가져오기
        student = StudentInfo.objects.get(user_id=self.request.user.id)
        university_id = student.university_id
        context['student_department'] = student.major.name

        # 강의에서 학과 데이터
        departments = Lecture.objects.values('opened_department').order_by('opened_department').distinct()
        context['department_list'] = departments

        # 강의에서 이수구분 데이터
        divisions = CompletionDivision.objects.filter(university_id=university_id)
        context['division_list'] = divisions

        #강의 학년 학기 필터링
        # 임시 2013년 1학기(10)

        lectures = Lecture.objects.filter(
            opened_year=2013,
            opened_semester=10,
            subject__university_id=university_id
        )

        #페이지네이션
        page = self.request.GET.get('page', 1)

        paginator = Paginator(lectures, 15)
        try:
            lecture_list = paginator.page(page)
        except PageNotAnInteger:
            lecture_list = paginator.page(1)
        except EmptyPage:
            lecture_list = paginator.page(paginator.num_pages)

        current_page = int(page) if page else 1
        page_numbers_range = 5
        max_index = len(paginator.page_range)

        start_index = int((current_page - 1) / page_numbers_range) * page_numbers_range
        end_index = start_index + page_numbers_range
        if end_index >= max_index:
            end_index = max_index

        page_range = paginator.page_range[start_index:end_index]
        context['page_range'] = page_range

        context['lecture_list'] = lecture_list
        return context

class ScheduleUV(DefaultMixin, LoginRequiredMixin, UpdateView):
    model = Schedule
    template_name = 'schedule_form.html'
    fields = ('name', 'lectures')
    active = 'scheduleActive'
    success_url = '/schedule/'

university/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponseRedirect
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView
from rest_framework.viewsets import ReadOnlyModelViewSet, ModelViewSet
from rest_framework.permissions import IsAuthenticated

from student.models import StudentInfo
from student.mixin import DefaultMixin, StaffRequiredMixin
from .models import University, CompletionDivision, Area, Track, \
    Department, Community
from .serializers import DepartmentSerializer, UniversitySerializer, CommunitySerilaizer,\
    CompletiondivisionSerializer, AreaSerializer, TrackSerializer
from .forms import UniversityForm, DepartmentForm

# Create your views here.

'''
대학 CRU UI 
'''
class UniversityLV(DefaultMixin, StaffRequiredMixin, ListView):
    model = University
    template_name = 'university_list.html'
    active = 'universityActive'

class UniversityCV(DefaultMixin, StaffRequiredMixin, CreateView):
    model = University
    template_name = 'university_form.html'
    form_class = UniversityForm
    active = 'universityActive'
    success_url = '/university/'

class UniversityUV(DefaultMixin, StaffRequiredMixin, UpdateView):
    model = University
    template_name = 'university_form.html'
    form_class = UniversityForm
    active = 'universityActive'
    success_url = '/university/'

class UniversityDeleteV(DefaultMixin, StaffRequiredMixin, DeleteView):
    model = University
    active = 'universityActive'
    success_url = '/university/'

    # get 막기 ( API처럼 사용 )
    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

'''
대학정보 (이수구분, 영역, 트랙) CRU UI
'''

class UniversityDataLV(DefaultMixin, StaffRequiredMixin, ListView):
    model = University
    template_name = 'university_data_list.html'
    active = 'universityDataActive'

    #정보 갯수 넘기기
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

class UniversityDataDV(DefaultMixin, StaffRequiredMixin, DetailView):
    model = University
    template_name = 'university_data_detail.html'
    active = 'universityDataActive'

'''
학과 데이터 CRU UI
'''

class DepartmentUniversityLV(DefaultMixin, StaffRequiredMixin, ListView):
    model = University
    template_name = 'department_university_list.html'
    active = 'departmentActive'

class DepartmentLV(DefaultMixin, StaffRequiredMixin, ListView):
    model = Department
    template_name = 'department_list.html'
    active = 'departmentActive'

    def get_queryset(self):
        return Department.objects.filter(university=self.kwargs['university'])

class DepartmentCV(DefaultMixin, StaffRequiredMixin, CreateView):
    model = Department
    template_name = 'department_form.html'
    active = 'departmentActive'
    form_class = DepartmentForm

    # Form에 대학 정보 넣어주기 위함
    def get_form_kwargs(self, *args, **kwargs):
        kwargs = super().get_form_kwargs(*args, **kwargs)
        kwargs['university'] = StudentInfo.objects.get(user_id=self.request.user.id).university_id
        return kwargs

    # 저장할때 대학 정보 추가
    def form_valid(self, form):
        self.object = form.save(commit=False)
        # things
        self.object.university_id = self.kwargs['university']
        self.object.save()

        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse('department_list', args=(self.object.university_id, ))

class DepartmentUV(DefaultMixin, StaffRequiredMixin, UpdateView):
    model = Department
    template_name = 'department_form.html'
    active = 'departmentActive'
    form_class = DepartmentForm

    # Form에 대학 정보 넣어주기 위함
    def get_form_kwargs(self, *args, **kwargs):
        kwargs = super().get_form_kwargs(*args, **kwargs)
        kwargs['university'] = StudentInfo.objects.get(user_id=self.request.user.id).university_id
        return kwargs

    # 저장할때 대학 정보 추가
    def form_valid(self, form):
        self.object = form.save(commit=False)
        # things
        self.object.university_id = self.kwargs['university']
        self.object.save()

        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse('department_list', args=(self.object.university_id,))

class DepartmentDeleteV(DefaultMixin, StaffRequiredMixin, DeleteView):
    model = Department

    # get 막기 ( API처럼 사용 )
    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('department_list', args=(self.object.university_id,))

'''
커뮤니티 그룹
'''

class CommunityLV(DefaultMixin, StaffRequiredMixin, ListView):
    model = Community
    template_name = 'community_list.html'
    active = 'communityGroupActive'


'''

api 

'''

class DepartmentViewset(ReadOnlyModelViewSet):
    queryset = Department.objects.all()
    serializer_class = DepartmentSerializer

    def get_queryset(self):
        university = self.request.query_params.get('university')
        return Department.objects.filter(university=university)

class UniversityGradeViewset(ReadOnlyModelViewSet):
    queryset = University.objects.all()
    serializer_class = UniversitySerializer
    permission_classes = (IsAuthenticated, )

class CommunityViewset(ModelViewSet):
    queryset = Community.objects.all()
    serializer_class = CommunitySerilaizer

class DivisionViewset(ModelViewSet):
    queryset = CompletionDivision.objects.all()
    serializer_class = CompletiondivisionSerializer

class AreaViewset(ModelViewSet):
    queryset = Area.objects.all()
    serializer_class = AreaSerializer

class TrackViewset(ModelViewSet):
    queryset = Track.objects.all()
    serializer_class = TrackSerializer

templates/department_university_list.html
{% load static %}
{% include "include/header.html" %}

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
      <section class="content-header">
          <h1>학과관리-학교리스트
            <small>Manage University List</small>
          </h1>
          <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> 학과관리-학교리스트</a></li>
          </ol>
      </section>
    <!-- Content Header (Page header) -->
    <section class="content container-fluid">

      <div class="col-md-12">
        <div class="box box-primary">
          <div class="box-header with-border">
            <h4>학과관리-학교리스트</h4>
          </div>
          <div class="box-body">
            <div class="col-md-12">
                <table class="table table-bordered table-striped table-hover text-center">
                    <thead>
                        <tr>
                            <th class="col-md-5">대학</th>
                            <th class="col-md-7">학과 갯수</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for university in university_list %}
                        <tr onclick="document.location='{% url 'department_list' university=university.id %}'">
                            <td>{{ university.name }}</td>
                            <td>{{ university.department_set.count }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
          </div>
          <div class="box-footer"></div>
        </div>
      </div>

      <!--------------------------
        | Your Page Content Here |
        -------------------------->

    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

{% include "include/footer.html" %}

templates/index.html
{% load static %}
{% include "include/header.html" %}

  <div class="content-wrapper">

    camp 서비스 설명

  </div><!-- /.content-wrapper -->

{% include "include/footer.html" %}

templates/rule_specific_list.html
{% load static %}
{% include "include/header.html" %}

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
      <section class="content-header">
          <h1>세부 졸업요건 - 대학명
            <small>Detailed Graduation List</small>
          </h1>
          <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> 세부 졸업요건 - 대학명</a></li>
          </ol>
      </section>
    <!-- Content Header (Page header) -->
    <section class="content container-fluid">

      <div class="col-md-12">
        <div class="box box-primary">
          <div class="box-header">
            <h4>세부 졸업요건 - {{ current_university.name }}</h4>
          </div>
          <div class="box-body">
            <div class="col-md-12">
              <div class="form-group col-md-3">
                <label>입학년도</label>
                <select id="search_year" class="form-control select2">
                            {% for year in years %}
                                <option value="{{ year.0 }}"
                                {% if year.0 == current_year %}selected{% endif %}
                                >{{ year.1 }}</option>
                            {% endfor %}
                </select>
              </div>
              <div class="form-group col-md-3">
                <label>학과</label>
                <select id="search_department" class="form-control select2">
                            {% for department in departments %}
                                <option value="{{ department.id }}"
                                {% if department.id == current_department.id %}selected{% endif %}
                                >{{ department.name }}</option>
                            {% endfor %}
                </select>
              </div>
              <div class="form-group col-md-3">
                <label>이수트랙</label>
                <select id="search_track" class="form-control select2">
                            {% for track in tracks %}
                                <option value="{{ track.id }}"
                                {% if track.id == current_track %}selected{% endif %}
                                >{{ track.name }}</option>
                            {% endfor %}
                </select>
              </div>
              <form id="search_form" method="get" action="">{% csrf_token %}
                    <button onclick="search_submit()" class="btn btn-primary col-md-3" style="margin-top:24px">조회</button>
                    </form>
              <table class="table table-bordered table-striped table-hover text-center">
                <thead>
                  <tr>
                    <th>졸업요건 이름</th>
                    <th>상위 졸업요건 이름</th>
                    <th>수정 졸업 요건 이름</th>
                    <th>요건 종류</th>
                    <th>요건 값</th>
                    <th>관리</th>
                  </tr>
                </thead>
                <tbody>
                {% for rule in rulespecific_list %}
                    <tr>
                    <td>{{ rule.name }}</td>
                    <td>{{ rule.upper_rule.name }}</td>
                    <td>{{ rule.change_rule.name }}</td>
                    <td>{{ rule.get_type_display }}</td>
                    <td>{{ rule.value }}</td>
                    <td>
                      <a href="{% url 'rule_specific_update' university=current_university.id year=current_year department=current_department.id pk=rule.id %}">
                          <button class="btn btn-warning btn-xs">수정</button></a>
                        <form class="btn btn-xs" onsubmit="submitResult('{{ rule.name }}')" method="post" action="{% url 'rule_specific_delete' university=current_university.id year=current_year department=current_department.id pk=rule.id %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger btn-xs">삭제</button>
                        </form>
                    </td>
                  </tr>
                {% endfor %}
                  <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>
                       <a href="{% url 'rule_specific_add' university=current_university.id year=current_year department=current_department.id %}">
                                <button class="btn btn-primary btn-xs">추가</button></a>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
          <div class="box-footer"></div>
        </div>
      </div>

      <!--------------------------
        | Your Page Content Here |
        -------------------------->

    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
<script>

    function submitResult(name){
        if( confirm(name+"을 정말 삭제하시겠습니까?")==false ){
            return false;
        }else{
            return true;
        }
    }

    function search_submit(){
        var year = $('#search_year').val()
        var track = $('#search_track').val()
        var department = $('#search_department').val()
        var action = '/graduation/rule/university/specific/1/'+year+'/'+department+'/'+track+'/'

        $('#search_form').attr('action',action)
        $('#search_form').submit()
    }
</script>

{% include "include/footer.html" %}

templates/subject_group_list.html
{% load static %}
{% include "include/header.html" %}

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
      <section class="content-header">
          <h1>과목그룹 관리
            <small>Subject Group Management</small>
          </h1>
          <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> 과목그룹 관리</a></li>
          </ol>
      </section>
    <!-- Content Header (Page header) -->
    <section class="content container-fluid">

      <div class="col-md-12">
        <div class="box box-primary">
          <div class="box-header with-border">
            <h4>과목그룹 관리</h4>
          </div>
          <div class="box-body">
                <div class="col-md-12">
                    <div class="form-group col-md-8">
                        <label>대학교</label>
                        <form id="search_form" method="get" action="">{% csrf_token %}
                        <select id="search_select" onchange="form_submit()" class="form-control select2">
                            {% for university in university_list %}
                                <option value="{{ university.id }}"
                                        {% if university.id == current_university %}selected{% endif %}>{{ university.name }}</option>
                            {% endfor %}
                        </select>
                        </form>
                    </div>
                    <a href="{% url 'subject_group_add' university=current_university %}"><button class="btn btn-primary col-md-4" style="margin-top:24px">생성</button></a>
                </div>
                <div class="col-md-12">
                    <table class="table table-bordered table-striped table-hover text-center">
                        <thead>
                            <tr>
                                <th class="col-md-4">과목그룹 이름</th>
                                <th class="col-md-5">이수구분 리스트</th>
                                <th style="width:100px">관리</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for subjectgroup in subjectgroup_list %}
                            <tr>
                                <td>{{ subjectgroup.name }}</td>
                                <td>{% for division in subjectgroup.completion_divisions.all %}[{{ division.name }}]{% endfor %}</td>
                                <td>
                                    <a href="{% url 'subject_group_update' university=current_university pk=subjectgroup.id %}">
                                        <button class="btn btn-warning btn-xs">수정</button></a>
                                    <form onsubmit="submitResult('{{ subjectgroup.name }}')" class="btn btn-xs" method="post" action="{% url 'subject_group_delete' university=current_university pk=subjectgroup.id %}">{% csrf_token %}
                                        <button type="submit" class="btn btn-danger btn-xs">삭제</button></form>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="box-footer">
            </div>
          </div>

        </div>
    </section>


      <!--------------------------
        | Your Page Content Here |
        -------------------------->


    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
<script>

    function submitResult(name){
        if( confirm(name+"을 정말 삭제하시겠습니까?")==false ){
            return false;
        }else{
            return true;
        }
    }

    function form_submit(){
        var action = "/graduation/subject/group/"
        action += $('#search_select').val()+'/'
        $('#search_form').attr('action', action)
        $('#search_form').submit()
    }

</script>

{% include "include/footer.html" %}

templates/university_data_list.html
{% load static %}
{% include "include/header.html" %}

  <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <section class="content-header">
                <h1>이수구분/영역/트랙
                  <small>Division/Area/Track</small>
                </h1>
                <ol class="breadcrumb">
                  <li><a href="#"><i class="fa fa-dashboard"></i> 이수구분/영역/트랙</a></li>
                </ol>
        </section>
    <!-- Content Header (Page header) -->
        <section class="content container-fluid">
            <div class="col-md-12">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h4>이수구분/영역/트랙</h4>
                    </div>
                    <div class="box-body">
                        <div class="col-md-12">
                            <table class="table table-bordered table-striped table-hover text-center">
                                <thead>
                                    <tr>
                                        <th class="col-md-3">대학명</th>
                                        <th class="col-md-3">이수구분 갯수</th>
                                        <th class="col-md-3">영역 갯수</th>
                                        <th class="col-md-3">트랙 갯수</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% for university in university_list %}
                                    <tr onclick="document.location='{% url 'university_data_detail' pk=university.id %}'">
                                        <td>{{ university.name }}</td>
                                        <td>{{ university.completiondivision_set.count }}</td>
                                        <td>{{ university.area_set.count }}</td>
                                        <td>{{ university.track_set.count }}</td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="box-footer"></div>
                </div>
            </div>

          <!--------------------------
            | Your Page Content Here |
            -------------------------->

        </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

{% include "include/footer.html" %}